language: ruby
sudo: required
services:
  - docker
before_install:
  - sudo sh -c 'echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" > /etc/apt/sources.list.d/docker.list'
  - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - sudo apt-get update
  - sudo apt-key update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine=1.11.1-0~precise
  - docker -v
  - docker pull exorath/mapservice
  - docker run -d -p 0.0.0.0:8080:8080 -e PORT=8080 -e AWS_REGION -e AWS_ACCESS_KEY_ID -e AWS_SECRET_KEY -e BUCKET_NAME exorath/mapservice
  - docker ps
script:
  - version=${TRAVIS_TAG-latest} ;
    if [ "$TRAVIS_TAG" == "" ]; then
    version=latest;
    fi ;
    sleep 10;
    curl http://localhost:8080/;
    docker ps;
    docker help build;
    docker build --build-arg GITHUB_OAUTH=${GITHUB_OAUTH} --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_KEY=${AWS_SECRET_KEY} --build-arg EULA=${EULA} --build-arg AWS_REGION=${AWS_REGION}  -t build-image . ;
    docker create --name=build-container build-image cat;
    docker cp build-container:/usr/src/mcserver ./mcserver;
    ls -lha ./mcserver;
    docker build -f Dockerfile.release -t $REPO:${version} .
after_success:
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    echo "version $TRAVIS_TAG" ;
    docker push "$REPO:$TRAVIS_TAG" ;
    fi 
