FROM openjdk:8-jdk

COPY ./mcserver/. /usr/src/mcserver/
COPY ./mcserver/startserver /usr/bin/
WORKDIR /usr/src/mcserver
RUN cp startserver /usr/bin/
#RUN apt-get update && apt-get install -y --no-install-recommends screen && rm -rf /var/lib/apt/lists/*
RUN arch="$(dpkg --print-architecture | awk -F- '{ print $NF }')" && wget -O gosu "https://github.com/tianon/gosu/releases/download/1.10/gosu-$arch" && chmod +x gosu

ENTRYPOINT ["gosu", "root", "startserver"]
