apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: server-simple1v1
  labels:
    app: server-simple1v1
spec:
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: server-simple1v1
    spec:
      containers:
      - name: server-simple1v1
        image: exorath/server-simple1v1:v0.0.10
        ports:
        - containerPort: 25565
          protocol: TCP
        env:
        - name: CONNECTOR_SERVICE_ADDRESS
          value: "localhost:8080"
        - name: PLAYERS_SERVICE_ADDRESS
          value: "localhost2:8080"
